spring.mail.host=smtp.gmail.com
spring.datasource.url=jdbc:postgresql://localhost:5432/db_auth
spring.datasource.username=adm_auth
spring.datasource.password=auth@api
spring.mail.port=587
spring.mail.username=kassimeridwane9@gmail.com
spring.mail.password=tftheyvjytowafyd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.cloud.config.enabled=false
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true