spring.datasource.url=jdbc:postgresql://localhost:5433/db_menage
spring.datasource.username=adm_menage
spring.datasource.password=menage@api
eureka.client.service-url.defaultZone=http://service-register:8761/eureka