spring.datasource.url=jdbc:postgresql://db-programme:5432/db_programme
spring.datasource.username=adm_programme
spring.datasource.password=programme@api
eureka.client.service-url.defaultZone=http://service-register:8761/eureka