spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=menage-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://MENAGE-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/menage/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[2].id=programme-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://PROGRAMME-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/programme/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1

eureka.client.service-url.defaultZone=http://service-register:8761/eureka